
require('./accept')
require('./acceptCharset')
require('./acceptEncoding')
require('./acceptLanguage')
require('./charset')
require('./cookies')
require('./get')
require('./has')
require('./headers')
require('./host')
require('./is')
require('./length')
require('./protocol')
require('./query')
require('./querystring')
require('./secure')
require('./type')
