
require('./append')
require('./body')
require('./etag')
require('./get')
require('./is')
require('./last-modified')
require('./length')
require('./message')
require('./redirect')
require('./remove')
require('./reset')
require('./set')
require('./status')
require('./type')
